# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
   "Screenshot 6.9 iPhone",
   "Screenshot 13 iPad"
])

languages([
   "en-US","zh-Hans","ja","pt-BR","en-GB","de-DE","fr-FR","es-MX","ko",
   "ru","es-ES","it","en-CA","en-AU","zh-Hant","tr","ar-SA","nl-NL",
   "pl","id","th","vi","hi","sv","pt-PT","da","no","fi","cs","fr-CA"
   ]
)

# The name of the scheme which contains the UI Tests
scheme("AgInOlUITests")

# Where should the resulting screenshots be stored?
output_directory("fastlane/screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
